version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
    install:
      - requirements: requirements.txt
      - requirements: requirements-dev.txt
      - requirements: requirements-doc.txt
