#!/bin/sh

set -e

cd "$(dirname "$0")/.."

echo "## bootstrap ###################################################################"
script/bootstrap

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

. "$VENV_NAME/bin/activate"

echo "## environment & versions ######################################################"
python --version
pip --version

echo "## clean up ####################################################################"
find octodns tests -name "*.pyc" -exec rm {} \;
rm -f *.pyc
echo "## begin #######################################################################"
# For now it's just lint...
echo "## lint ########################################################################"
script/lint
echo "## tests/coverage ##############################################################"
script/coverage
echo "## validate setup.py build #####################################################"
python setup.py build
echo "## validate setup.py install ###################################################"
deactivate
TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)
python3 -m venv $TMP_DIR
. "$TMP_DIR/bin/activate"
python setup.py install
octodns-sync --help
echo "## validate tests can run against installed code ###############################"
pip install pytest pytest-network
pytest --disable-network
echo "## complete ####################################################################"
