#!/bin/bash

echo "## bootstrap ###################################################################"
script/bootstrap

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

echo "## environment & versions ######################################################"
python --version
pip --version
echo "## modules: "
pip freeze
echo "## clean up ####################################################################"
find octodns tests* -name "*.pyc" -exec rm {} \;
rm -f *.pyc
echo "## begin #######################################################################"
# For now it's just lint...
echo "## lint ########################################################################"
script/lint
echo "## formatting ##################################################################"
script/format --check || (echo "Formatting check failed, run ./script/format" && exit 1)
echo "## tests/coverage ##############################################################"
script/coverage
echo "## complete ####################################################################"
