#!/bin/sh
set -e

cd "$(dirname "$0")/.."

echo "## bootstrap ###################################################################"
script/bootstrap

echo "## environment & versions ######################################################"
python --version
pip --version
VVER=$(virtualenv --version)
echo "virtualenv $VVER"

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

. "$VENV_NAME/bin/activate"

echo "## clean up ####################################################################"
find octodns tests -name "*.pyc" -exec rm {} \;
rm -f *.pyc
echo "## begin #######################################################################"
# For now it's just lint...
echo "## lint ########################################################################"
script/lint
echo "## tests/coverage ##############################################################"
script/coverage
echo "## complete ####################################################################"
