#!/bin/bash

set -e

SOURCES_PYTHON="$(find *.py octodns tests -name '*.py') $(grep --files-with-matches '^#!.*python' script/*)"
SOURCE_MARKDOWN="$(find *.md docs examples -name '*.md')"

. env/bin/activate

isort "$@" $SOURCES_PYTHON
black "$@" $SOURCES_PYTHON

if [[ "$*" =~ check ]]; then
    mdformat --check --compact-tables --number $SOURCE_MARKDOWN
else
    mdformat --compact-tables --number $SOURCE_MARKDOWN
fi
