#!/bin/sh
set -e

cd "$(dirname "$0")/.."
ROOT=$(pwd)

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

ACTIVATE="$VENV_NAME/bin/activate"
if [ ! -f "$ACTIVATE" ]; then
    echo "$ACTIVATE does not exist, run ./script/bootstrap" >&2
    exit 1
fi
. "$ACTIVATE"

cd docs

if [ -z "$BUILDER" ]; then
    BUILDER=html
fi

build="_build/${BUILDER}"
rm -rf "$build" api/records/ api/processors/

sphinx-build --builder "$BUILDER" --conf-dir . --fail-on-warning "$@" "." "$build"
